### ISSUE TITLE
add a License

### ISSUE THREAD

**Issue by jamie-roberts** [NHSH-MRI-Physics/Scottish-Medium-ACR-Analysis-Framework#14]
I tried to find a license file but was unsuccessful (sorry if I missed it). Do you plan to add a LICENSE.TXT file? It would be easier to use your project if it was licensed e.g. MIT or otherwise.

FYI 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by DrSpacemanMD** [comment]
Thanks for the feedback a licence has been added now.
